### ISSUE TITLE
Bad time of sunrise and sunset

### ISSUE THREAD

**Issue by pierpe83** [SensorsIot/SleepAccelerator#2]
Hello.
I spent a few hours on it and I do not know what's going on.
My ESP still reads the wrong sunrise and sunset times from the server. All time of sunrise and sunset hours are distorted by two hours.
At https://sunrise-sunset.org/api I have valid hours for my location.
I'm sure I have the correct location entered in the sketch.
Please help Andreas.

**Comment by pierpe83** [comment]
I checked the co-ordinates from your sketch and also gives incorrect hours.

**Comment by SensorsIot** [comment]
https://youtu.be/VdpvAeVAeY0?t=274 I mention that the time the API returns is in UTC. Because I also get the actual time in UTC you do not need to adjust the time zone. If you want to use the call for another application you have to correct the time zone.
